#!/usr/bin/env ruby

forge "https://forge.puppetlabs.com"

# Modules from the Puppet Forge
mod 'puppetlabs-stdlib', '4.6.0'
mod 'puppetlabs-apt', '2.1.0'
mod 'puppetlabs-apache', '1.11.0'
mod 'ghoneycutt-common', '1.2.1'
mod 'puppetlabs-ntp', '4.0.0'
mod 'ghoneycutt-ssh', '3.24.0'
mod 'darin-zypprepo', '1.0.2'
mod 'rnelson0-hiera_resources', '1.0.0'
mod 'thias-sysctl', '1.0.2'
mod 'puppetlabs-inifile', '1.4.2'

# Modules from GitHub
mod 'mayflower-php',
  :git => 'git://github.com/willaerk/puppet-php.git',
  :ref => '22fddde'

mod 'rodjek-logrotate',
  :git => 'git://github.com/rodjek/puppet-logrotate.git',
  :ref => '89ee645'

mod 'puppetlabs-concat',
  :git => 'git://github.com/puppetlabs/puppetlabs-concat.git',
  :ref => '2518958'

mod 'saz-sudo',
  :git => 'git://github.com/saz/puppet-sudo.git',
  :ref => 'be624a8'

mod 'stankevich-python',
  :git => 'git://github.com/stankevich/puppet-python.git',
  :ref => '952403f'

mod 'puppetlabs-vcsrepo',
  :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo.git',
  :ref => 'd08d16b'

mod 'maestrodev-wget',
  :git => 'git://github.com/maestrodev/puppet-wget.git',
  :ref => '33a60ee'

mod 'puppetlabs-firewall',
  :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git',
  :ref => 'b2eae73'

mod 'puppetlabs-git',
  :git => 'git://github.com/puppetlabs/puppetlabs-git.git',
  :ref => '4afcea8'

mod 'puppet-icinga2',
  :git => 'git://github.com/icinga/puppet-icinga2.git',
  :ref => '2f37544'

mod 'cultuurnet-cultuurnet',
  :git => 'git://github.com/cultuurnet/puppet-cultuurnet.git',
  :ref => '6828875'

mod 'cultuurnet-cacert',
  :git => 'git://github.com/cultuurnet/puppet-cacert.git',
  :ref => '0.1.3'

mod 'cultuurnet-mailcatcher',
  :git => 'git://github.com/cultuurnet/puppet-mailcatcher.git',
  :ref => '2f0e9d6'
